# Generated by Django 4.1.5 on 2023-01-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=15)),
                ('updated_by', models.CharField(max_length=15)),
                ('datamode', models.CharField(choices=[('A', 'ACTIVE'), ('IN', 'INACTIVE'), ('D', 'DELETED')], db_index=True, default='A', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Super Admin', 'SUPER ADMIN'), ('Admin', 'ADMIN'), ('Operators', 'OPERATORS'), ('Technicians', 'TECHNICIANS')], db_index=True, default='Technicians', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=15)),
                ('updated_by', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=15)),
                ('updated_by', models.CharField(max_length=15)),
                ('datamode', models.CharField(choices=[('A', 'ACTIVE'), ('IN', 'INACTIVE'), ('D', 'DELETED')], db_index=True, default='A', max_length=12)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziago_app.members')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziago_app.roles')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziago_app.roles'),
        ),
    ]
