# Generated by Django 4.1.5 on 2023-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziago_app', '0002_alter_members_table_alter_rights_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='user_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
