# Generated by Django 4.1.5 on 2023-01-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziago_app', '0003_members_user_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='datamode',
        ),
        migrations.RemoveField(
            model_name='rights',
            name='member',
        ),
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='members',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rights',
            table=None,
        ),
        migrations.AlterModelTable(
            name='roles',
            table=None,
        ),
    ]
