# Generated by Django 4.1.5 on 2023-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziago_app', '0004_remove_rights_datamode_remove_rights_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='member_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
