# Generated by Django 4.1.5 on 2023-01-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziago_app', '0006_remove_members_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rights',
            name='role',
        ),
        migrations.AddField(
            model_name='rights',
            name='role',
            field=models.ManyToManyField(to='ziago_app.roles'),
        ),
    ]
